# Generated by Django 4.2.7 on 2023-12-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
