# Generated by Django 4.2.7 on 2023-12-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_times', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='fim_projeto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
